SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS workflow_actions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS workflow_definitions;
DROP TABLE IF EXISTS executors;
DROP TABLE IF EXISTS workflow;
SET FOREIGN_KEY_CHECKS=1;
